# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/nisitha/My_Passport/MOODLE/Vivado_projects/audio_zybo/zybo_audio_dsp/zybo_audio_dsp/zybo_audio_dsp.srcs/sources_1/ip/oddr_0/oddr_0.xci
# IP: The module: 'oddr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/audio_zybo/zybo_audio_dsp/zybo_audio_dsp/zybo_audio_dsp.gen/sources_1/ip/oddr_0/oddr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oddr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/nisitha/My_Passport/MOODLE/Vivado_projects/audio_zybo/zybo_audio_dsp/zybo_audio_dsp/zybo_audio_dsp.srcs/sources_1/ip/oddr_0/oddr_0.xci
# IP: The module: 'oddr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/audio_zybo/zybo_audio_dsp/zybo_audio_dsp/zybo_audio_dsp.gen/sources_1/ip/oddr_0/oddr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oddr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
