# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/nisitha/My_Passport/MOODLE/Vivado_projects/audio_zybo/zybo_audio_dsp/zybo_audio_dsp/zybo_audio_dsp.srcs/sources_1/ip/fir_filter_fixed_coeff_drom/fir_filter_fixed_coeff_drom.xci
# IP: The module: 'fir_filter_fixed_coeff_drom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/audio_zybo/zybo_audio_dsp/zybo_audio_dsp/zybo_audio_dsp.gen/sources_1/ip/fir_filter_fixed_coeff_drom/fir_filter_fixed_coeff_drom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_fixed_coeff_drom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/nisitha/My_Passport/MOODLE/Vivado_projects/audio_zybo/zybo_audio_dsp/zybo_audio_dsp/zybo_audio_dsp.srcs/sources_1/ip/fir_filter_fixed_coeff_drom/fir_filter_fixed_coeff_drom.xci
# IP: The module: 'fir_filter_fixed_coeff_drom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/nisitha/My_Passport/MOODLE/Vivado_projects/audio_zybo/zybo_audio_dsp/zybo_audio_dsp/zybo_audio_dsp.gen/sources_1/ip/fir_filter_fixed_coeff_drom/fir_filter_fixed_coeff_drom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_fixed_coeff_drom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
